name: TheMovieApp
options:
  bundleIdPrefix: com.guilherme.TheMovieApp

targets:
  TheMovieApp:
    preBuildScripts:
      - path: swiftgen.sh
        name: Swiftgen
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: [TheMovieApp]